version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo "[Install] Nothing extra to install for plain PHP app"

  pre_build:
    commands:
      - echo "[Pre‑Build] $(date)"

  build:
    commands:
      - echo "[Build] No compilation needed"

  post_build:
    commands:
      - echo "[Post‑Build] Completed at $(date)"

artifacts:
  files:
    - '**/*'
  discard-paths: yes
  exclude-paths:
    - .git/**
    - php-login-app.zip
