version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo "[Install] Using PHP 8.1"

  pre_build:
    commands:
      - echo "[Pre-Build] Started at $(date)"

  build:
    commands:
      - echo "[Build] Checking PHP version..."
      - php -v
      - echo "[Build] No compilation needed for PHP"

  post_build:
    commands:
      - echo "[Post-Build] Finished at $(date)"

artifacts:
  files:
    - '**/*'
  discard-paths: yes
  exclude-paths:
    - .git/**
    - php_projct.zip

